---
title: Geanimeerd verhaal
hero_image: images/banner.png
description: Gebruik JavaScript intersection observers om een sprookjesachtige website tot leven te brengen!
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - title: Inleiding
  - title: Elementen observeren
  - title: Afbeeldingen traag laden
    completion:
      - engaged
  - title: Nieuwe pagina toevoegen
  - title: Tekst animeren
  - title: Animeer het verhaal
    completion:
      - internal
  - title: Reflectie
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Wat kun je verder nog doen?
