---
title: animated-story
hero_image: images/banner.png
description: Use JavaScript intersection observers to add life to a storybook website!
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Observing elements
- title: Lazy-loading images
- title: Add a new page
- title: Animate text
- title: Animate the story
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Upgrade your project
- title: What next?
