---
title: Histoire animée
hero_image: images/banner.png
description: Utilise les Intersection Observer en JavaScript pour ajouter de la vie à un site web de conte de fées !
version: 4
listed: true
copyedit: false
last_tested: '2021-03-26'
steps:
  - title: Introduction
  - title: Observation des éléments
  - title: Images à chargement lent
    completion:
      - engaged
  - title: Ajouter une nouvelle page
  - title: Animer le texte
  - title: Animer l'histoire
    completion:
      - internal
  - title: Réflexion
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Et ensuite ?
